### ISSUE TITLE
redeem-currents: make sure biz-name is saving in the form

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#1023]
@dannypernik biz-name entered in the popup is currently not part of the form (the popup needs to make it inside the form tags). I am hoping you can help resolve this so we can save this field in the db.

**Comment by dannypernik** [comment]
@nickolashe the value of the field in the popup is copied into the `{{ form.master_biz_name }}` input (disabled) into #master-offer-details on 'screen 1' of redeem-currents. #master-offer-details is only shown on template if the "Next" in master-offer-popup is clicked. So `master_biz_name` should be collected from form, not `biz_name` from the popup. It isn't necessary to use forms.py with the popup input since it's not in the form and I've handled the only unhappy path (blank biz name) in JS logic.

**Comment by nickolashe** [comment]
@dannypernik can you take a close look at my commit please. i renamed master_biz_name form field to biz_name in forms.py. i'd like your help with getting this to work as you've set up the extra logic of copying the fields from popup to form.

**Comment by dannypernik** [comment]
@nickolashe you can close if we're good here

**Comment by nickolashe** [comment]
@dannypernik it does appear you have tested your changes

**Comment by nickolashe** [comment]
https://github.com/opencurrents/opencurrents/pull/1016/commits/542cbe8e7819ecd73078e32e5095ce37b0747de4
