### ISSUE TITLE
invite-volunteers: regression when inviting to future events

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#1025]
Invite Volunteer - Event Future
Url: https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/urls.py#L110

Volunteers in DB with no password - don't receive event email and don't get added to the event. (Proper functionality should be: receive event email "new" and added to event)
Volunteers in DB with password - don't receive event email and don't get added to the event. (Proper functionality should be: receive event email "existing" and added to event)
New Volunteers not in DB - receive event email "new" and get added to event (This is proper functionality)

**Comment by MaxTattenbach** [comment]
@tevtonez Emails are being passed along properly, the issue is that users in the DB with and without a password are not being added to the event. 

costasverdes@gmail.com  = in DB w/ password
maxtattenbach@gmail.com =   in DB w/out password
testopencurrents@gmail.com = not in db

![image](https://user-images.githubusercontent.com/26234440/35280769-cf9bd3e8-0016-11e8-8dbc-33e6d864d80e.png)

![image](https://user-images.githubusercontent.com/26234440/35280840-03522e1c-0017-11e8-9bb5-6136eef04dc3.png)

![image](https://user-images.githubusercontent.com/26234440/35280868-17aa8c06-0017-11e8-99d2-d12af81105ef.png)

![image](https://user-images.githubusercontent.com/26234440/35281134-cee17326-0017-11e8-830c-7348444098c0.png)

**Comment by tevtonez** [comment]
@MaxTattenbach I see where the issue is. I'm fixing and testing the fix.
