### ISSUE TITLE
live-dashboard: Track admin who checks in volunteer

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#114]
Associate admin to each check-in and check-out; also track who approves hours of hours submitted by a volunteer

**Comment by nickolashe** [comment]
@karbmk reassigning this one to you

**Comment by dannypernik** [comment]
@nickolashe will we need an additional data field that saves the approving admin for each usertimelog?

**Comment by nickolashe** [comment]
correct, so this will require adding the field to the `UserTimeLog` model

**Comment by nickolashe** [comment]
@dannypernik @karbmk along the same lines, i think lets go ahead and start recording the admin id's that approve or decline hours. we can use the existing `DeferredUserTimes` for this purpose since it has just the right structure (we'll need to rename the table to something else to reflect this change)

**Comment by dannypernik** [comment]
@nickolashe where are we with this?

**Comment by nickolashe** [comment]
done
