### ISSUE TITLE
Multiple checkins of the same user: evaluate the entire sequence for the record that determines the true contributed time

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#153]

**Comment by dannypernik** [comment]
<img width="772" alt="screen shot 2017-07-11 at 11 34 12 am" src="https://user-images.githubusercontent.com/3347095/28079166-e7fc7548-662c-11e7-8a2c-63759f233d23.png">

@nickolashe Max and I tested live-dashboard with test org. When checking in to a past event, the checkbox click was recorded in the database (see above), but the total hours was not affected. Strange as this appears to be a different behavior from checking in volunteers to KAB's past event.

I think all three of us are on the same page that we want to simplify the event hours recorded. Max mentioned that orgs would currently record 2 hours for each volunteer attending a 2-hour event, and we can leave it at that. He mentioned even getting rid of check-out, so that when you view a past event, blue checks attended and grey checks did not, no exceptions. I tend to agree. If someone gives time before an event, they can add it manually. I think a volunteer can be checked in during the hour before the event but receive only the hours for the duration.

**Comment by nickolashe** [comment]
https://github.com/opencurrents/opencurrents/pull/182
