### ISSUE TITLE
On Admin Profile, the event is should be bold font, and a link to the event detal. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#221]
Note on Profile the event is bold, although not clickable. 

![issue 5 event not bold](https://user-images.githubusercontent.com/26234440/28692710-55a71c8a-72e7-11e7-9bc5-05c2ba5a50f6.PNG)

**Comment by dannypernik** [comment]
@MaxTattenbach agreed that we should link the text of upcoming events on profile to their event pages. The reason I decided to make location bold on admin-profile instead of event name is that an event with multiple locations will have everything the same except location and we want to make sure the admin accesses the correct location to check in volunteers.

**Comment by nickolashe** [comment]
what's the status of this one?

**Comment by dannypernik** [comment]
PR #255 I opted for a submenu instead of a link on the words itself so that the admin knows exactly where he/she is going. Open to making a link as well. When an admin is looking at the event-detail page I think we should remove the "Contact coordinator" field and "Register" button. Possibly replace with "Edit event". @nickolashe what conditional statement should I use so that only admins of the event's associated org displays the Edit button?

**Comment by nickolashe** [comment]
I don't think we need a conditional statement. Instead, on admin page we'll only show events for that org. On user profile there will be no edits regardless.

**Comment by dannypernik** [comment]
PR #261
