### ISSUE TITLE
Error handling forbidden access

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#276]
If user is not logged in and tries accessing forbidden page, send to /login with message, possibly "Please log in to access this page". But for this message we'd want to hold onto the attempted URL so that we could direct them to the attempted page after login. @nickolashe do you think this makes sense? I will say that I've always been frustrated when I try to visit a website, it makes me log in, then takes me to a totally different page. One scenario to consider is if the user still doesn't have access to the requested page even after logging in, we should send them to profile instead of 403. 

If user is logged in and tries accessing forbidden page, throw 403 error

**Comment by nickolashe** [comment]
do we have a 403 page ready?

**Comment by dannypernik** [comment]
@nickolashe we can use the 500 template for 403 or make a new one

**Comment by nickolashe** [comment]
403 is different in that its not a server error, so the error message needs to be different

**Comment by karbmk** [comment]
I tried DEBUG = False in settings which seems to work but distorts the UI totally. To avoid distortion insecure parameter could be used but that's not an option since it's make the website inefficient. I also researched and saw that the server needs to take care of the static files when DEBUG is False. @nickolashe , Any idea how I could be able to solve this bug?

**Comment by nickolashe** [comment]
@karbmk yes, i am aware of such an issue. it's not hard to set it up. i'll take of it today.
