### ISSUE TITLE
Live-Dashboard: Invite volunteers should explicitly state its to the event. "KAB issues"

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#332]

**Comment by nickolashe** [comment]
mail email content focused on inviting to the event, not opencurrents

**Comment by nickolashe** [comment]
a link at the bottom to join opencurrents

**Comment by dannypernik** [comment]
@nickolashe @MaxTattenbach we need to change this email template to make volunteer coordinators more comfortable inviting volunteers from their email list. "Invite volunteer" is intended to invite them to openCurrents, not the event (they should already be at the event if checked in on live-dashboard). Perhaps we want to disable adding volunteers on this page before the event so that they use invite-volunteers instead (which sends invite-specific email). Max also pointed out that admins should be able to view a list of invited volunteers from invite-volunteers page.

**Comment by nickolashe** [comment]
ok, should we move this to the next bucket then?

**Comment by dannypernik** [comment]
Sounds good, we'll just need to do this before our next event with Keep Austin Beautiful

**Comment by dannypernik** [comment]
Yes, we'll just need this before our next event with Keep Austin Beautiful

**Comment by dannypernik** [comment]
We've created Issue #454 and decided live-dashboard is fine as is once invite-volunteers is working
