### ISSUE TITLE
time-tracker-new: nominate new org popup does not make sense

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#367]
after selecting a registered org and "someone else" in admin dropdown, i got a popup asking me if i "give time with a social organization not listed here". i think the message should be regarding inviting the admin to register on opencurrents.

**Comment by karbmk** [comment]
@dannypernik , @nickolashe. Can you guys also let me know about how the functionality should be implemented? details on like if the volunteer can nominate a person who is not in our website. If yes, how should we handle etc..

**Comment by dannypernik** [comment]
@karbmk @nickolashe I've removed the popup trigger when "Someone else" is selected. Instead of tying the popup to a select option, I've added a link at the bottom of time-tracker. See time-tracker_new branch.

Yes, a volunteer can nominate anyone but we won't send them an email. Instead, we will want to send new-org-nominated template to bizdev@opencurrents.com:

<img width="400" alt="screen shot 2017-08-26 at 2 43 17 am" src="https://user-images.githubusercontent.com/3347095/29739654-bb45579a-8a08-11e7-8ab6-2845519d2d05.png">
