### ISSUE TITLE
Offer Page #1:  General Comments. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#464]
A few recomendations

1. Lets change "Intro" to "Getting Started"
2. Lets re-arrange the button of Got-it to the right. Note that in all the other pages Next is on the right. 
3. Lets increase the discount in the example to $100 so its $80 and 2 Currents. 

![offer page - 1](https://user-images.githubusercontent.com/26234440/30401410-c944a940-989f-11e7-8683-d900df6c6e8a.PNG)

**Comment by dannypernik** [comment]
1. "Getting started" is too long for mobile. Intro seems fine
2. I'd need to remove "Contact us" which I'm ok with. Since people read from left to right I want them to read "Got it" first after the explanation. Let me know if this sounds good. But I also think it's fine to leave as is, especially since the user hasn't seen the back/next buttons yet.
3. Done
