### ISSUE TITLE
Redeem Currents:  General Flow

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#473]
I suggest we create three steps for redeem Currents, after clicking in one particular offer.   Very simple steps divided as follows. 

Let me know your thoughts. 

1.  Price Paid: Price paid to merchant.  In this case you volunteer we will list the price for the item he is wanting to redeem Currents for
2.  Proof-of Purchase:  Upload receipt or "no receipt".  If there is "no receipt" we must show a pop-up which  say's there is a probability that the vendor won't want to buy your Currents if its not easy enough for him to determine the transaction.  
3.  Confirm: Agree to exchange X #  of Currents for XX USD with XXX Vendor.   - This is the automated logic that we talked about.

**Comment by dannypernik** [comment]
@MaxTattenbach done: https://openc.herokuapp.com/redeem-currents 

Feel free to suggest additional changes. @nickolashe check out the "Choose images" button. Choosing a file changes the name of the text. But then if you click it again and hit cancel instead of hitting another file, the text goes blank. My hypothesis is that the first file is still sitting in the input. Would you be able to test if this is correct?
