### ISSUE TITLE
org-admin: Show manually tracked hours pending or approved

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#479]
Designed in `org_hours` branch

**Comment by nickolashe** [comment]
pending is approve-hours, isn't it?

**Comment by nickolashe** [comment]
@dannypernik can you elaborate

**Comment by dannypernik** [comment]
@nickolashe you're right, I think we should just have a section for approved hours in admin-profile. Should we include declined hours too?

**Comment by MaxTattenbach** [comment]
I guess there are two types of pending.

Pending to be approved:  In-case a volunteer submits hours and have not yet
been approved.

Pending to approve: In-case an admin receives hours and needs to approve.
I think both Pending should be in personal profiles as they are directly
related to an individual and not to the Organization.

Thoughts?




Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by nickolashe** [comment]
@MaxTattenbach do you mean the former should be shown on the volunteer profile while the other on the admin profile?

**Comment by nickolashe** [comment]
https://github.com/opencurrents/opencurrents/issues/499

**Comment by nickolashe** [comment]
@dannypernik sounds good on showing approved / declined

**Comment by MaxTattenbach** [comment]
@nickolashe, I am Ok with the pop-up if that's how its designed.  I think pop-up should display on the "user profile" rather than on the "Admin Org" profile.  See definitions that I suggest below.    

@dannypernik @nickolashe   I am needing some clarity around definitions of profiles; I don't think we formally defined them. I think it is important to have clarity around this.    

User Profile = The profile that everyone has once they open an account.  Id rather not call it volunteer profile because I think it can lead to confusions. 
Org Admin Profile =  The profile a user has access to once he gets admin status to an non-profit.  I believe each one of these is unique to the "user-org"; of the specific Org.   
Biz Admin Profile = The profile a user has access to once he gets admin status to a Business.  I believe each one of these is unique to the "user-org" of the specific business  
Org Profile = Profile of the Org (I don't think we currently have an Org Profile; as in one that looks that same no matter the admin) 
Biz Profile = Profile of the Business  (I don't think we currently have an Org Profile; as in one that looks that same no matter the admin)

**Comment by nickolashe** [comment]
agreed on the profile defs @MaxTattenbach. I am not sure which popup you are talking about though - I don't think I mentioned any popups

**Comment by MaxTattenbach** [comment]
The pop-up admins see when they have pending hours to approve.

Lets from now also talk about pending hours in the following way.

Pending Currents:  Status of Currents when hours are submitted by Volunteer
to Org-Admin. Seen in the User Profile as "Pending Currents"

Pending Hours: Status of Hours to be approved Org-Admins.  At the moment I
believe these show up as a pop-up in the User Profile when User has hours
to approve in the Org-Admin Profile.  We should probably have an email of
remainder to the Org-Admins to approve hours once a week.




Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by dannypernik** [comment]
https://opencdesign.herokuapp.com/org-admin (probably need to be logged in first)
