### ISSUE TITLE
marketplace: List offers

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#480]
Agree on design. How are we going to order offers?

**Comment by nickolashe** [comment]
by date issued

**Comment by dannypernik** [comment]
@nickolashe Are you thinking newest offer first? I guess that would put our first vendors at a disadvantage. I know you and @MaxTattenbach didn't love the idea of ordering by Current share but it seems like volunteers would like to see where to get the most value for their time and it would offer an appropriate incentive to businesses. Open to options.

**Comment by MaxTattenbach** [comment]
I think it should be the order should be by which ever business has the
most Currents in their account.  But date works fine for MVP.



Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by nickolashe** [comment]
@MaxTattenbach oh, sounds somewhat unfair :)

**Comment by nickolashe** [comment]
lets do date for the MVP, not that many offers yet

**Comment by dannypernik** [comment]
Alright I'd like to revisit once we have more than a page of offers.

**Comment by MaxTattenbach** [comment]
It works for me.

**Comment by MaxTattenbach** [comment]
Agree with @dannypernik lets revisit in next stage.

**Comment by MaxTattenbach** [comment]
Note that it makes sense to grant benefits to those that own lots of
Currents.  It's like paying for adds if you own Currents. :)

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by dannypernik** [comment]
@MaxTattenbach this would bias the offer list towards bigger businesses that have more customers at the expense of small local businesses/startups that should be at the core of our community. I assume this is what @nickolashe was getting at when he mentioned it seems unfair.

Listing offers based on % of Currents accepted would create the incentive while keeping a level playing field for big and small vendors.

**Comment by MaxTattenbach** [comment]
@dannypernik @nickolashe I guess no need to discuss more as we have agreed they would be ordered by date on MVP. 

@dannypernik - note that if ordered by Current share you may have very unpopular products listed first in the market  place just because nobody wants them.  Usually market places tend to orders products based on popularity.  

I also think that owning Currents is what brings value to our ecosystem and should be valued by openCurrents.  The more Currents business owns the better and should be rewarded.  If not we are saying value it ain't valuable for us.     A good way to order could be based on the following criteria popularity (# transactions), Currents owned (Currents Owned),  and then Current Share.   

Lets leave it for later.

**Comment by dannypernik** [comment]
agreed to leave for later
