### ISSUE TITLE
Crowdsource messaging

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#519]
Lets brainstorm on how we can display a few pop-up's reminding/incentivizing users to help us grow the network.

**Comment by dannypernik** [comment]
@nickolashe I've created the popup in profile.html on develop branch. It auto-opens due to this line:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/templates/profile.html#L403

We'll need to add conditional logic that only opens the popup if they haven't answered the question (it's currently possible to click outside the popup and not answer the question. We could force an answer if we wished.)

If we go through a forms.py example together with edit-event or another template, I could hook up this form if you'd like.

**Comment by nickolashe** [comment]
sure sounds good, lets find a time this week to step though an example. i am currently occupied with pr #582 so any help on other fronts would be much appreciated.

**Comment by dannypernik** [comment]
Max's Proposed Text from #599:

Welcome to the openCurrents community. We are just getting started and your contribution to growing our community is essential. If you would like to help our community grow by referring your favorite nonprofits, businesses, friends or even influencers please opt-in. You could also receive brand ambassador status. One of our members will be in touch with you shortly. Let's change this World one Current at a time!

Designed previously:
<img width="633" alt="screen shot 2017-10-30 at 12 12 16 pm" src="https://user-images.githubusercontent.com/3347095/32184994-f9b39474-bd6b-11e7-9530-e7012b621f6e.png">

**Comment by dannypernik** [comment]
Agreed text with Max:
<img width="635" alt="screen shot 2017-10-30 at 1 33 03 pm" src="https://user-images.githubusercontent.com/3347095/32188868-fdc55cf4-bd76-11e7-8b8d-6e9394c7a267.png">

**Comment by dannypernik** [comment]
dup of #741
