### ISSUE TITLE
biz-admin:  Eliminate buttons of Accept/Decline

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#573]
The idea is good but may be outside of the scope of MVP.    Unless we really want the vendor to accept or decline from his profile for MVP.  I don't think this has been discussed as part of the requirements.  

@dannypernik @nickolashe  What are your thoughts?   Definitely, a nice to have but not a must-have to prove the concept.  

![image](https://user-images.githubusercontent.com/26234440/31856898-0a613b8e-b694-11e7-9642-87c90f59dc72.png)

**Comment by nickolashe** [comment]
It should not be hard to have them approve / decline

**Comment by dannypernik** [comment]
@nickolashe @MaxTattenbach I think we can get rid of these buttons because we don't want a business to have to log in and accept/decline offers one by one. Perhaps the easiest way would be to have one page that shows all of the receipt images and a decline button next to each. Kind of like approve-hours, I think we should have one Accept button. We could even have that button say "Accept X offers, decline Y"

**Comment by nickolashe** [comment]
have we agreed to remove the buttons for requests backed by receipts altogether?

**Comment by MaxTattenbach** [comment]
Yes for the meantime.  If we have time we can add later.

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by nickolashe** [comment]
@MaxTattenbach when you create a new issue, can you please follow the above format (prefixing with the actual name of the page)
