### ISSUE TITLE
redeem-currents:  Amount minus fees must be listed on confirmation.  End user will need to agree to accept the amount minus fees.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#593]

**Comment by nickolashe** [comment]
@dannypernik are you able to make this change?

**Comment by dannypernik** [comment]
@nickolashe yes, but we need to agree on the transaction fee. 10% @MaxTattenbach ?

**Comment by MaxTattenbach** [comment]
I am inclined for 20% but lets discuss today. I came up with a good idea.

**Comment by dannypernik** [comment]
Note this is for 25% Current share and recorded price of $12.34:

<img width="636" alt="screen shot 2017-10-26 at 6 37 17 pm" src="https://user-images.githubusercontent.com/3347095/32081761-e67637b4-ba7c-11e7-8a12-84b57a65a996.png">

Note that the Currents exchange amount rounds to 3 digits, while the precise calculation would be 0.3085 Currents. I think 3 decimals is reasonable since dollars:currents is 10:1 and dollars are rounded to 2 digits. Also I believe @nickolashe has used 3 decimal rounding in other places for Currents. Here's the calculation:

<img width="725" alt="screen shot 2017-10-26 at 6 41 38 pm" src="https://user-images.githubusercontent.com/3347095/32081847-58d39e46-ba7d-11e7-8bec-9c9b9b587b69.png">

**Comment by MaxTattenbach** [comment]
Three decimal on Currents seems fine when they are present. If no decimal
then let's not show three decimal points.

I suggest we replace text to:

I agree to exchange 0.308 C for $2.77 Dollars. Note: Add question mark next
to dollars (?)  - If they click we can illustrate the breakdown of fees.

A total of $2.77 Pending Dollars will be added to your account while 0.308
C will be deducted.  Once Keep Austin Beautiful validates the transaction
at the end of the month Pending Dollars will become Available Dollars,
which you can then transfer to your bank account. We will notify you via
email once confirmed.



Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by nickolashe** [comment]
@dannypernik i think i've seen this change implemented already or am i wrong?

**Comment by dannypernik** [comment]
yes in develop
