### ISSUE TITLE
Biz-admin: Lets also add pending Balance (C) and Available Balance (C)

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#634]
Note:  Currently pending balance is missing.   All the offers redeemed should be displayed as pending Currents. 

![image](https://user-images.githubusercontent.com/26234440/32417931-34366b62-c226-11e7-8302-33d1755643cc.png)

**Comment by dannypernik** [comment]
<img width="869" alt="screen shot 2017-11-07 at 8 57 57 pm" src="https://user-images.githubusercontent.com/3347095/32529465-61ac4006-c3fe-11e7-845e-63bb59e3d879.png">
How does this look? I brought the offer button center to keep the balance of the page now that the right heading has 2 lines of its own. (There will be more info on Currents requested below this screenshot; this issue is just for the balances)

**Comment by dannypernik** [comment]
This change is in `layouts` branch in layouts/admin.html (this layout's blocks show biz-admin's profile by default)

**Comment by nickolashe** [comment]
@dannypernik move over to another branch based off `nicko` and open to a PR to it

**Comment by dannypernik** [comment]
@nickolashe this is now working, correct?

**Comment by MaxTattenbach** [comment]
@nickolashe @dannypernik,  I think this can be closed.  Seems to be working on develop server
