### ISSUE TITLE
profile: Total Redeemed Currents are displayed in "Redeemed Currents" button, under Community Activity

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#697]

**Comment by MaxTattenbach** [comment]
@maxtattenbach recheck currents accepted vs. currents reedeed

**Comment by dannypernik** [comment]
@MaxTattenbach

**Comment by MaxTattenbach** [comment]
@nickolashe  I believe you had changed the logic so that we actually see the Currents been submitted for redemption under community activity.   The Currents accepted button doesn't seem to be updating nor does the public record.

![image](https://user-images.githubusercontent.com/26234440/34328961-a84d8e7c-e8b4-11e7-805a-dd7425bd3224.png)

![image](https://user-images.githubusercontent.com/26234440/34328983-fb04f736-e8b4-11e7-87ae-eafc2f965b7d.png)

**Comment by nickolashe** [comment]
@MaxTattenbach pushed what i think is the last change required, can you give it another try pls

**Comment by MaxTattenbach** [comment]
@nickolashe redeemed currents are still not showing in the profile nor public record.  Note that this use to be working beforehand about two weeks ago. 

![image](https://user-images.githubusercontent.com/26234440/34420748-d5b6f01e-ebd0-11e7-9dc7-63ee3e1da932.png)

![image](https://user-images.githubusercontent.com/26234440/34420804-2a17ec1c-ebd1-11e7-9083-187175a31f34.png)

**Comment by MaxTattenbach** [comment]
@nickolashe note that this is working properly to master.  Please advice on what we should do with this issue.
