### ISSUE TITLE
Org-Admin: Hours Tracked header not adding the hours of Envents

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#804]

**Comment by MaxTattenbach** [comment]
Note: An event of 10 hours was created, Org hours tracked should have increased from 44.5 to 64.5.  

![image](https://user-images.githubusercontent.com/26234440/33776481-1fc9bf80-dc07-11e7-9a20-acce03213669.png)

**Comment by nickolashe** [comment]
@tevtonez the issue is likely due to summing times based on usertimelogs, not events (as discussed):
https://github.com/opencurrents/opencurrents/blob/kostya_profile_additions/openCurrents/interfaces/community.py#L53
https://github.com/opencurrents/opencurrents/blob/kostya_profile_additions/openCurrents/interfaces/community.py#L63

**Comment by nickolashe** [comment]
lets change all time references to those based of event start and end time everywhere
