### ISSUE TITLE
Can't access admin profile when linking email to org on backed end. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#927]
@nickolashe I have linked a user on the backend created the org user and then granted him access but this particular user can't access the org. 

![image](https://user-images.githubusercontent.com/26234440/34427249-c530f854-ec05-11e7-9ec9-38d86c5c1874.png)

![image](https://user-images.githubusercontent.com/26234440/34427274-25d87fa6-ec06-11e7-9113-b5c3592efd7b.png)

![image](https://user-images.githubusercontent.com/26234440/34427284-4115b310-ec06-11e7-9270-44664305e1fc.png)

![image](https://user-images.githubusercontent.com/26234440/34427255-d71a4afc-ec05-11e7-8424-9c63e94e40d9.png)

**Comment by dannypernik** [comment]
@MaxTattenbach I guess you're working on oC.com here since Costas verdes is org id 61 there. Perhaps you forgot to click "Save" after assigning your user to admin group, as your affiliation is not appearing there:
<img width="879" alt="screen shot 2018-01-02 at 6 56 54 pm" src="https://user-images.githubusercontent.com/3347095/34506015-bf6c2032-efee-11e7-9c2d-95aa27e87fbc.png">

**Comment by nickolashe** [comment]
@tevtonez we need to make sure instead of a runtime error user is directed to `/403` in this case.

**Comment by tevtonez** [comment]
@nickolashe good point! I added the needed code in acdf72a and 53be9e1

**Comment by nickolashe** [comment]
@MaxTattenbach in develop

**Comment by MaxTattenbach** [comment]
@nickolashe @tevtonez this is working now!
