### ISSUE TITLE
org-admin: Remove extra decimal point on hours totals per admin

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#957]
Low priority.

<img width="266" alt="screen shot 2018-01-02 at 11 55 29 pm" src="https://user-images.githubusercontent.com/3347095/34510316-807e0e42-f018-11e7-83eb-9bd3f56a722f.png">

**Comment by nickolashe** [comment]
this would involve extra logic on the backend. more importantly, i thought we decided to have three decimal places for currents. you wouldn't normally round $10.20 to $10.2, would you?

**Comment by MaxTattenbach** [comment]
@dannypernik @nickolashe I think we should always use two decimal points for hours and Currents. 
It does look somewhat weird to have three decimal points for hours. 

I think this needs some discussion will add a new label.

**Comment by nickolashe** [comment]
@MaxTattenbach reason why we decided to go with 3 is due to the exchange rate. for example, when converting $10.23 to currents you while keeping precision down to 2 places you'd end up with C1.02. converting back you'd loose the 3 cents. we can choose to keep the precision on the backend but only show 2 decimal places - this would be a simple change.

**Comment by dannypernik** [comment]
@nickolashe @MaxTattenbach I'm ok with leaving 3 decimal places for Currents. However it doesn't make sense to show 3 decimal places for hours since we are rounding to the nearest .25 hours anyway.

**Comment by nickolashe** [comment]
yes, we made the change for hours.
